# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('homeworld', models.TextField(blank=True, null=True)),
                ('films', models.TextField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('vehicles', models.TextField(blank=True, null=True)),
                ('starships', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
