# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0002_auto_20190509_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
