# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-09 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('year_of_manufacturing', models.DateField(verbose_name='Year Of Manufacturing')),
                ('car_type', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green')], default='blue', max_length=100)),
                ('car_color', models.CharField(choices=[('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('crossover', 'Crossover'), ('sports utility vehicle', ' Sports Utility Vehicle')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-date_created'],
            },
        ),
    ]
