# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green')], default='blue', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('crossover', 'Crossover'), ('sports utility vehicle', ' Sports Utility Vehicle')], max_length=100),
        ),
    ]
